
# commun parameters :
IP_ESP8266wifi =  '192.168.1.100' 
INIT_SPPED = 30
MOTOR_DOWN  = 'MOTORDOWN'
MOTOR_UP = 'MOTORUP'
MOTOR_STOP = 'MOTORSTOP'
MOTOR_SPEED = 'MOTORSPEED'
RADAR_ON = 'RADARON'
RADAR_OFF = 'RADAROFF'
